name: CI

on:
  pull_request: []

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup black environment
        run: conda create --quiet --name black pyflakes

      - name: Check formatting with black
        run: |
          export PATH="/usr/share/miniconda/bin:$PATH"
          source activate black
          pip install black==20.8b1
          black --check django_river_ml

      - name: Check imports with pyflakes
        run: |
          export PATH="/usr/share/miniconda/bin:$PATH"
          source activate black

          pyflakes django_river_ml/announce.py
          pyflakes django_river_ml/apps.py
          pyflakes django_river_ml/auth.py
          pyflakes django_river_ml/client.py
          pyflakes django_river_ml/exceptions.py
          pyflakes django_river_ml/flavors.py
          pyflakes django_river_ml/__init__.py
          pyflakes django_river_ml/middleware.py
          pyflakes django_river_ml/model.py
          pyflakes django_river_ml/namer.py
          pyflakes django_river_ml/signals.py
          pyflakes django_river_ml/storage.py
          pyflakes django_river_ml/urls.py
          pyflakes django_river_ml/utils.py
          pyflakes django_river_ml/version.py
          pyflakes django_river_ml/views/auth.py
          pyflakes django_river_ml/views/base.py
          pyflakes django_river_ml/views/learn.py
          pyflakes django_river_ml/views/metrics.py
          pyflakes django_river_ml/views/model.py
          pyflakes django_river_ml/views/predict.py

  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup testing environment
        run: conda create --quiet --name testing pytest

      - name: Django Tests
        run: |
          export PATH="/usr/share/miniconda/bin:$PATH"
          source activate testing
          pip install -r tests/requirements.txt
          # TODO TESTS NOT WRITTEN YET
          #python manage.py makemigrations django_river_ml
          #python manage.py makemigrations
          #python manage.py migrate
          #python manage.py migrate django_river_ml
          #echo ::group::tests.test_api
          #python manage.py test tests.test_api
          #echo ::endgroup::tests.test_api
          #rm db-test.sqlite3
